language: java

jdk:
  - oraclejdk8

sudo:
  - required

os:
  - linux

services:
  - docker
  - mongodb

branches:
  except:
    - /^feature-.*$/

before_install:
  - openssl aes-256-cbc -pass pass:$PGP_KEY_PASSWORD -in ./.ci/secring.gpg.enc -out ~/secring.gpg -d -md md5
  - chmod a+x gradlew
  - chmod a+x ./.ci/build.sh
  - chmod a+x ./.ci/prepare-travis.sh
  - chmod a+x ./.ci/release.sh
  - . ./.ci/prepare-travis.sh

before_script:
  - rm nitrite-datagate/src/main/resources/application.properties

install: true

script:
  - travis_retry . ./.ci/build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - travis_retry . ./.ci/release.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - $TRAVIS_BUILD_DIR/nitrite-datagate/src/main/dist/nitrite-datagate-$NITRITE_VERSION.zip
    - $TRAVIS_BUILD_DIR/nitrite-explorer/build/libs/nitrite-explorer-$NITRITE_VERSION.jar
  on:
    tags: true

env:
  global:
    - NITRITE_VERSION=4.0.0-SNAPSHOT
    - PGP_KEY_FILE=~/secring.gpg
